spring:
  application:
    name: customer-service
  cloud:
    config:
      import-check:
        enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/servicem
    username: ${DATA_BASE_USR}
    password: ${DATA_BASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
server:
  port: 8092
  error:
    include-message: always
management:
  tracing:
    sampling:
      probability: 1.0
